/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 04-may.-2019 15:54:34 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `Department` CASCADE
;

DROP TABLE IF EXISTS `Post` CASCADE
;

DROP TABLE IF EXISTS `Professor` CASCADE
;

DROP TABLE IF EXISTS `Professor-Subject` CASCADE
;

DROP TABLE IF EXISTS `Subject` CASCADE
;

DROP TABLE IF EXISTS `User` CASCADE
;

/* Create Tables */

CREATE TABLE `Department`
(
	`idDept` VARCHAR(5) NOT NULL,
	`nombre` VARCHAR(20) NOT NULL,
	CONSTRAINT `PK_Department` PRIMARY KEY (`idDept` ASC)
)

;

CREATE TABLE `Post`
(
	`idPost` VARCHAR(10) NOT NULL,
	`date` VARCHAR(10) NOT NULL,
	`comments` VARCHAR(200) NULL,
	`verification` BOOL NOT NULL,
	`idProfessor` VARCHAR(12) NOT NULL,
	`idSubject` VARCHAR(12) NOT NULL,
	`file` BLOB NULL,
	`solution` BLOB NULL,
	CONSTRAINT `PK_Post` PRIMARY KEY (`idPost` ASC)
)

;

CREATE TABLE `Professor`
(
	`idProfessor` VARCHAR(12) NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`idSubject` VARCHAR(10) NULL,
	CONSTRAINT `PK_Professor` PRIMARY KEY (`idProfessor` ASC)
)

;

CREATE TABLE `Professor-Subject`
(
	`idSubject` VARCHAR(10) NOT NULL,
	`idProfessor` VARCHAR(12) NOT NULL,
	CONSTRAINT `PK_Professor-Subject` PRIMARY KEY (`idSubject` ASC, `idProfessor` ASC)
)

;

CREATE TABLE `Subject`
(
	`idSubject` VARCHAR(10) NOT NULL,
	`name` VARCHAR(20) NOT NULL,
	`idDept` VARCHAR(5) NULL,
	`idProfessor` VARCHAR(12) NULL,
	CONSTRAINT `PK_Subject` PRIMARY KEY (`idSubject` ASC)
)

;

CREATE TABLE `User`
(
	`idUser` VARCHAR(12) NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`user` VARCHAR(50) NOT NULL,
	`password` VARCHAR(36) NOT NULL,
	`userType` VARCHAR(10) NOT NULL,
	`idPost` VARCHAR(10) NULL,
	CONSTRAINT `PK_User` PRIMARY KEY (`idUser` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `Post` 
 ADD INDEX `IXFK_Post_Subject` (`idSubject` ASC)
;

ALTER TABLE `Professor` 
 ADD INDEX `IXFK_Professor_Professor-Subject` (`idSubject` ASC, `idProfessor` ASC)
;

ALTER TABLE `Subject` 
 ADD INDEX `IXFK_Subject_Department` (`idDept` ASC)
;

ALTER TABLE `Subject` 
 ADD INDEX `IXFK_Subject_Professor-Subject` (`idSubject` ASC, `idProfessor` ASC)
;

ALTER TABLE `User` 
 ADD INDEX `IXFK_User_Post` (`idPost` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `Post` 
 ADD CONSTRAINT `FK_Post_Subject`
	FOREIGN KEY (`idSubject`) REFERENCES `Subject` (`idSubject`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Professor` 
 ADD CONSTRAINT `FK_Professor_Professor-Subject`
	FOREIGN KEY (`idSubject`, `idProfessor`) REFERENCES `Professor-Subject` (`idSubject`,`idProfessor`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Subject` 
 ADD CONSTRAINT `FK_Subject_Department`
	FOREIGN KEY (`idDept`) REFERENCES `Department` (`idDept`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Subject` 
 ADD CONSTRAINT `FK_Subject_Professor-Subject`
	FOREIGN KEY (`idSubject`, `idProfessor`) REFERENCES `Professor-Subject` (`idSubject`,`idProfessor`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `User` 
 ADD CONSTRAINT `FK_User_Post`
	FOREIGN KEY (`idPost`) REFERENCES `Post` (`idPost`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
; 
